name: ServerFabric-Client
version: 0.1.0
main: dev.jumpwatch.serverfabric.client.DynClientPlugin
api-version: "1.20"
commands:
  serf:
    description: Open ServerFabric GUI
    usage: /serf
permissions:
  serf.gui:
    default: op
